export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
//WOMEN PAGE CONSTANT
export const PRODUCT_WOMENCAT_LIST_REQUEST = 'PRODUCT_ WOMENCAT_LIST_REQUEST';
export const PRODUCT_WOMENCAT_LIST_SUCCESS = 'PRODUCT_ WOMENCAT_LIST_SUCCESS';
export const PRODUCT_WOMENCAT_LIST_FAIL = 'PRODUCT_WOMENCAT_LIST_FAIL';
// MEN PAGE CONSTANT
export const PRODUCT_MENCAT_LIST_REQUEST = 'PRODUCT_ MENCAT_LIST_REQUEST';
export const PRODUCT_MENCAT_LIST_SUCCESS = 'PRODUCT_ MENCAT_LIST_SUCCESS';
export const PRODUCT_MENCAT_LIST_FAIL = 'PRODUCT_MENCAT_LIST_FAIL';
// KIDS PAGE CONSTANT
export const PRODUCT_KIDSCAT_LIST_REQUEST = 'PRODUCT_ KIDSCAT_LIST_REQUEST';
export const PRODUCT_KIDSCAT_LIST_SUCCESS = 'PRODUCT_ KIDSCAT_LIST_SUCCESS';
export const PRODUCT_KIDSCAT_LIST_FAIL = 'PRODUCT_KIDSCAT_LIST_FAIL';
// news page constatnt
export const PRODUCT_NEWCAT_LIST_REQUEST = 'PRODUCT_ NEWCAT_LIST_REQUEST';
export const PRODUCT_NEWCAT_LIST_SUCCESS = 'PRODUCT_ NEWCAT_LIST_SUCCESS';
export const PRODUCT_NEWCAT_LIST_FAIL = 'PRODUCT_NEWCAT_LIST_FAIL';
// accesso page constant
export const PRODUCT_ACCESSOCAT_LIST_REQUEST = 'PRODUCT_ ACCESSOCAT_LIST_REQUEST';
export const PRODUCT_ACCESSOCAT_LIST_SUCCESS = 'PRODUCT_ ACCESSOCAT_LIST_SUCCESS';
export const PRODUCT_ACCESSOCAT_LIST_FAIL = 'PRODUCT_ACCESSOCAT_LIST_FAIL';
// COSMETICS page constant
export const PRODUCT_COSMTCAT_LIST_REQUEST = 'PRODUCT_ COSMTCAT_LIST_REQUEST';
export const PRODUCT_COSMTCAT_LIST_SUCCESS = 'PRODUCT_ COSMTCAT_LIST_SUCCESS';
export const PRODUCT_COSMTCAT_LIST_FAIL = 'PRODUCT_COSMTCAT_LIST_FAIL';
// EVERYDAY page constant
export const PRODUCT_EVERYDAYCAT_LIST_REQUEST = 'PRODUCT_ EVERYDAYCAT_LIST_REQUEST';
export const PRODUCT_EVERYDAYCAT_LIST_SUCCESS = 'PRODUCT_ EVERYDAYCAT_LIST_SUCCESS';
export const PRODUCT_EVERYDAYCAT_LIST_FAIL = 'PRODUCT_EVERYDAYCAT_LIST_FAIL';
// GADGETS page constant
export const PRODUCT_GADGETSCAT_LIST_REQUEST = 'PRODUCT_ GADGETSCAT_LIST_REQUEST';
export const PRODUCT_GADGETSCAT_LIST_SUCCESS = 'PRODUCT_ GADGETSCAT_LIST_SUCCESS';
export const PRODUCT_GADGETSCAT_LIST_FAIL = 'PRODUCT_GADGETSCAT_LIST_FAIL';
// toyes page constant
export const PRODUCT_TOYESCAT_LIST_REQUEST = 'PRODUCT_ TOYESCAT_LIST_REQUEST';
export const PRODUCT_TOYESCAT_LIST_SUCCESS = 'PRODUCT_ TOYESCAT_LIST_SUCCESS';
export const PRODUCT_TOYESCAT_LIST_FAIL = 'PRODUCT_TOYESCAT_LIST_FAIL';
// sales page constant
export const PRODUCT_SALECAT_LIST_REQUEST = 'PRODUCT_ SALECAT_LIST_REQUEST';
export const PRODUCT_SALECAT_LIST_SUCCESS = 'PRODUCT_ SALECAT_LIST_SUCCESS';
export const PRODUCT_SALECAT_LIST_FAIL = 'PRODUCT_SALECAT_LIST_FAIL';
// PRODUCT DETAIL PAGE CONSTANT
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
// PRODCTS UPLOAD PAGE CONSTANT
export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_SEARCH_LIST_REQUEST = 'PRODUCT_SEARCH_LIST_REQUEST';
export const PRODUCT_SEARCH_LIST_SUCCESS = 'PRODUCT_SEARCH_LIST_SUCCESS';
export const PRODUCT_SEARCH_LIST_FAIL = 'PRODUCT_SEARCH_LIST_FAIL';

